vars:
  http_port: 4320
configurations:
  default:
    content:
      source:
        elasticsearch:
          endpoint: $vars.endpoint
          auth:
            authenticator: $vars.authenticator
          cache_duration: 10s
      opamp:
        protocols:
          http:
            endpoint: "localhost:$vars.http_port"